#!/bin/bash -ex

dl() {
    [[ "$FAB_HTTP_PROXY" ]] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

REPO=TracksApp/tracks
VERSION=$(gh_releases ${REPO} | grep -iv "ALPHA\|BETA\|RC" | sort -V | tail -1)
URL="https://github.com/${REPO}/archive/${VERSION}.tar.gz"

# previously releases we very slow, but things have improved now
#VERSION=master

SRC="/usr/local/src"
dl https://github.com/TracksApp/tracks/archive/${VERSION}.zip $SRC
mv $SRC/${VERSION}.zip $SRC/tracks-${VERSION}.zip
