#!/bin/bash -ex

dl() {
    [[ "$FAB_HTTP_PROXY" ]] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

#VERSION="v2.6.1"
# follow the lead of others and build from master - it has some sec updates
VERSION=master

SRC="/usr/local/src"
dl https://github.com/TracksApp/tracks/archive/${VERSION}.zip $SRC
mv $SRC/${VERSION}.zip $SRC/tracks-${VERSION}.zip
