#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/tracks

# start mysql
/etc/init.d/mysql start

# install tracks and configure it
unzip $SRC/tracks-*.zip -d $(dirname $WEBROOT)
rm $SRC/tracks-*.zip

mv $WEBROOT $WEBROOT.orig
mv $(dirname $WEBROOT)/tracks-* $WEBROOT
cp $WEBROOT.orig/config/database.yml $WEBROOT/config/database.yml
rm -rf $WEBROOT.orig

cp $WEBROOT/config/site.yml.tmpl $WEBROOT/config/site.yml

# update DB files to force DYMANIC row - work around Redmine/MariaDBv10.1 bug
cat > $WEBROOT/config/initializers/ar_innodb_row_format.rb <<EOF
ActiveSupport.on_load :active_record do
  module ActiveRecord::ConnectionAdapters
    class AbstractMysqlAdapter
      def create_table_with_innodb_row_format(table_name, options = {})
        table_options = options.reverse_merge(:options => 'ENGINE=InnoDB ROW_FORMAT=DYNAMIC')

        create_table_without_innodb_row_format(table_name, table_options) do |td|
         yield td if block_given?
        end
      end
      alias_method_chain :create_table, :innodb_row_format
    end
  end
end
EOF

cd $WEBROOT
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
bundle --without=test install
bundle exec rake db:migrate RAILS_ENV="production"
unset HTTP_PROXY

# configure permissions
mkdir -p $WEBROOT/tmp/cache
chown -R www-data:www-data $WEBROOT/tmp
chown -R www-data:www-data $WEBROOT/log
chmod 666 $WEBROOT/log/*

# precompile assets
bundle exec rake assets:precompile

# turnkey-credit (passenger substitute x2 bug)
cat >>$WEBROOT/app/assets/stylesheets/tracks.css.scss<<EOF
#turnkey-credit {
    font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif;
    font-size: 11px;
    text-align: center;
    padding-top: 5px;
}
#turnkey-credit a {
    text-decoration: none;
}
EOF

TURNKEY_CREDIT="<div id='turnkey-credit'> <div> <a href='https://www.turnkeylinux.org/tracks'>Tracks Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a> </div> </div>"

FOOTER=$WEBROOT/app/views/shared/_footer.html.erb
sed -i "s|</div>|$TURNKEY_CREDIT\n</div>|" $FOOTER

# stop mysql
/etc/init.d/mysql stop

