#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/tracks

# start mysql
/etc/init.d/mysql start

# install tracks and configure it
unzip $SRC/TracksApp-*.zip -d $(dirname $WEBROOT)
rm $SRC/TracksApp-*.zip

mv $WEBROOT $WEBROOT.orig
mv $(dirname $WEBROOT)/TracksApp* $WEBROOT
cp $WEBROOT.orig/config/database.yml $WEBROOT/config/database.yml
rm -rf $WEBROOT.orig

cp $WEBROOT/config/site.yml.tmpl $WEBROOT/config/site.yml

cd $WEBROOT
bundle install --local
rake db:migrate RAILS_ENV="production"

# configure permissions
mkdir -p $WEBROOT/tmp
chown -R root:www-data $WEBROOT
chown -R www-data:www-data $WEBROOT/tmp
chown -R www-data:www-data $WEBROOT/log
chown -R www-data:www-data $WEBROOT/public/stylesheets
chown -R www-data:www-data $WEBROOT/public/javascripts
chmod 666 $WEBROOT/log/*

# turnkey-credit (passenger substitute x2 bug)
cat >>$WEBROOT/public/stylesheets/standard.css<<EOF
#turnkey-credit {
    font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif;
    font-size: 11px;
    text-align: center;
    padding-top: 5px;
}
#turnkey-credit a {
    text-decoration: none;
}
EOF

TURNKEY_CREDIT="<div id='turnkey-credit'> <div> <a href='http://www.turnkeylinux.org/tracks'>Tracks Appliance</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a> </div> </div>"

FOOTER=$WEBROOT/app/views/shared/_footer.rhtml
sed -i "s|</div>|$TURNKEY_CREDIT\n</div>|" $FOOTER

# stop mysql
/etc/init.d/mysql stop
