#!/bin/sh -ex

RAILS_APP=railsapp

# start mysql
/etc/init.d/mysql start

# install tracks and configure it
unzip /usr/local/src/bsag-tracks-*.zip -d /var/www/
cd /var/www

mv $RAILS_APP $RAILS_APP.orig
mv bsag-tracks* $RAILS_APP
cp $RAILS_APP.orig/config/database.yml $RAILS_APP/config/
cp $RAILS_APP/config/site.yml.tmpl $RAILS_APP/config/site.yml

cd /var/www/$RAILS_APP
rake db:migrate RAILS_ENV="production"

mkdir -p /var/www/$RAILS_APP/tmp
mkdir -p /var/www/$RAILS_APP/public/stylesheets/cache
mkdir -p /var/www/$RAILS_APP/public/javascripts/cache

# configure permissions
chown -R root:www-data /var/www/$RAILS_APP
chown -R www-data:www-data /var/www/$RAILS_APP/tmp
chown -R www-data:www-data /var/www/$RAILS_APP/log
chown -R www-data:www-data /var/www/$RAILS_APP/public/stylesheets/cache
chown -R www-data:www-data /var/www/$RAILS_APP/public/javascripts/cache
chmod 666 /var/www/$RAILS_APP/log/*

# turnkey-credit (passenger substitute x2 bug)
cat >>/var/www/$RAILS_APP/public/stylesheets/standard.css<<EOF
#turnkey-credit {
    font-family: Tahoma,Sans,Arial,Helvetica,Verdana,sans-serif;
    font-size: 11px;
    text-align: center;
    padding-top: 5px;
}
#turnkey-credit a {
    text-decoration: none;
}
#turnkey-credit a:hover {
    text-decoration: underline;
}
EOF

TURNKEY_CREDIT="<div id='turnkey-credit'> <div> <a href='http://www.turnkeylinux.org/tracks'>Tracks Appliance</a> - Powered by <a href='http://www.turnkeylinux.org'>TurnKey Linux</a> </div> </div>"

FOOTER=/var/www/$RAILS_APP/app/views/shared/_footer.rhtml
sed -i "s|</div>|$TURNKEY_CREDIT\n</div>|" $FOOTER

# cleanup
rm /usr/local/src/bsag-tracks-*
rm -rf /var/www/$RAILS_APP.orig

# stop mysql
/etc/init.d/mysql stop
