#!/bin/bash

# patch for tracks 2.2 on ruby 1.8.7

CONTEXTS=/var/www/tracks/app/controllers/contexts_controller.rb

cat > $CONTEXTS.diff <<EOF
--- contexts_controller.rb.orig 2013-02-21 10:21:46.000000000 +0000
+++ contexts_controller.rb      2013-02-21 10:22:06.000000000 +0000
@@ -235,10 +235,7 @@
   def render_autocomplete
     lambda do
       # find contexts and the todos count. use a join to prevent all count(todos) of each context to be fetched
-      context_and_todo_count = current_user.contexts
-      .select('contexts.*, count(todos.id) as todos_count')
-      .joins('left outer join todos on context_id=contexts.id')
-      .group('context_id')
+      context_and_todo_count = current_user.contexts.select('contexts.*, count(todos.id) as todos_count').joins('left outer join todos on context_id=contexts.id').group('context_id')

       filled_contexts = context_and_todo_count.reject { |ctx| ctx.todos.size == 0 }
       empty_contexts = context_and_todo_count.find_all { |ctx| ctx.todos.size == 0 }
EOF

patch $CONTEXTS $CONTEXTS.diff
rm $CONTEXTS.diff

