#!/bin/bash -e
# regenerate tracks secrets

. /etc/default/inithooks

CONF_DIR=/var/www/tracks/config

# secret token
CONF=$CONF_DIR/site.yml
TOKEN="$( mcookie )$( mcookie )$( mcookie )$( mcookie )"
sed -i "/^secret_token/s|: .*$|: '$TOKEN'|" $CONF

# MySQL user password
DB_CONF=$CONF_DIR/database.yml
DB_PASS=$(mcookie)
$INITHOOKS_PATH/bin/mysqlconf.py --user=tracks --pass=$DB_PASS
sed -i "\|password:|s|:.*$|: $DB_PASS|g" $DB_CONF
