#!/bin/bash -e
# regenerate tracks secrets

. /etc/default/inithooks

# secret token
TOKEN="$( mcookie )$( mcookie )$( mcookie )$( mcookie )"
CONF='/var/www/tracks/config/site.yml'

sed -i "/^secret_token/s|: .*$|: '$TOKEN'|" $CONF

